Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 23/04/2024
Var
Contador:inteiro



Inicio
Contador:=1
Enquanto contador<=10 faca
Escreval("O contador é:",contador)
Contador:= contador+1
FimEnquanto


Fimalgoritmo